### ISSUE TITLE
zf5/stable/cm13.1/ZNH5Y

### ISSUE THREAD

**Issue by hungximbex9x** [intel-ctp/android#29]
Update readme.md

-repo init -u git://github.com/intel-ctp/android.git -b zf5/stable/cm-13.0-ZNH2Y
+repo init -u git://github.com/intel-ctp/android.git -b zf5/stable/cm-13.0-ZNH5Y

**Comment by dgadelha** [comment]
@leonardohenrique10 notified me before about this but I forgot.
Thanks for remiding! :)
